apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: us-central1-docker.pkg.dev/gcp-learning-01-463711/python-flask-microservices/service-b:latest
        ports:
        - containerPort: 8080